/**
 * Canonical seed data for investor profiles.
 * All data sourced from publicly available information (firm websites, Crunchbase, press).
 * Used by admin seed route and auto-seed logic.
 */

export interface SeedInvestor {
  name: string;
  type: string;
  website?: string;
  description?: string;
  stages: string;       // JSON string[]
  sectors: string;      // JSON string[]
  geographies: string;  // JSON string[]
  chequeMin?: number;
  chequeMax?: number;
  thesis?: string;
  notableDeals: string; // JSON string[]
  aum?: string;
  partnerCount?: number;
  linkedIn?: string;
  twitter?: string;
  source: string;
  verified: boolean;
  enabled: boolean;
}

export const SEED_INVESTORS: SeedInvestor[] = [
  // ─── TOP-TIER VC ───────────────────────────────────────────────────────
  {
    name: "Sequoia Capital",
    type: "vc",
    website: "https://www.sequoiacap.com",
    description: "Legendary VC backing iconic companies from idea stage to IPO. Known for partnering with daring founders who want to build legendary companies.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["enterprise", "fintech", "healthtech", "consumer", "crypto", "ai"]),
    geographies: JSON.stringify(["US", "Europe", "India", "Southeast Asia"]),
    chequeMin: 100000,
    chequeMax: 100000000,
    thesis: "We help the daring build legendary companies. From idea to IPO and beyond.",
    notableDeals: JSON.stringify(["Apple", "Google", "Airbnb", "Stripe", "WhatsApp", "Zoom", "DoorDash"]),
    aum: "$85B+",
    partnerCount: 30,
    linkedIn: "https://linkedin.com/company/sequoia-capital",
    twitter: "https://twitter.com/sequoia",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Andreessen Horowitz (a16z)",
    type: "vc",
    website: "https://a16z.com",
    description: "Full-stack VC firm providing capital, services, and expertise to founders. Strong focus on technology-driven transformation across industries.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["ai", "crypto", "enterprise", "fintech", "consumer", "bio", "gaming"]),
    geographies: JSON.stringify(["US", "Global"]),
    chequeMin: 500000,
    chequeMax: 150000000,
    thesis: "Software is eating the world. We back bold founders building the future with technology.",
    notableDeals: JSON.stringify(["Facebook", "GitHub", "Coinbase", "Lyft", "Databricks", "OpenAI"]),
    aum: "$42B+",
    partnerCount: 40,
    linkedIn: "https://linkedin.com/company/a16z",
    twitter: "https://twitter.com/a16z",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Accel",
    type: "vc",
    website: "https://www.accel.com",
    description: "Early and growth-stage venture capital firm with 40+ years of partnering with exceptional founders.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["saas", "enterprise", "fintech", "consumer", "security", "infrastructure"]),
    geographies: JSON.stringify(["US", "Europe", "India"]),
    chequeMin: 500000,
    chequeMax: 100000000,
    thesis: "We partner with exceptional founders from the earliest days through every phase of growth.",
    notableDeals: JSON.stringify(["Facebook", "Slack", "Spotify", "Dropbox", "UiPath", "Flipkart"]),
    aum: "$50B+",
    partnerCount: 20,
    linkedIn: "https://linkedin.com/company/accel-partners",
    twitter: "https://twitter.com/Accel",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Lightspeed Venture Partners",
    type: "vc",
    website: "https://lsvp.com",
    description: "Multi-stage VC accelerating disruptive innovations in enterprise, consumer, and health sectors globally.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["enterprise", "consumer", "healthtech", "fintech", "crypto"]),
    geographies: JSON.stringify(["US", "Europe", "India", "Israel", "Southeast Asia"]),
    chequeMin: 100000,
    chequeMax: 100000000,
    thesis: "We partner with extraordinary entrepreneurs to build enterprises that matter.",
    notableDeals: JSON.stringify(["Snap", "Affirm", "Mulesoft", "OYO", "Epic Games", "Grubhub"]),
    aum: "$18B+",
    partnerCount: 15,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Benchmark",
    type: "vc",
    website: "https://www.benchmark.com",
    description: "Early-stage VC known for equal partnership model and hands-on founder support. One of Silicon Valley's most selective firms.",
    stages: JSON.stringify(["seed", "series-a"]),
    sectors: JSON.stringify(["consumer", "enterprise", "marketplace", "saas"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 1000000,
    chequeMax: 20000000,
    thesis: "We invest early, work closely with founders, and build for the long term.",
    notableDeals: JSON.stringify(["eBay", "Twitter", "Uber", "Snap", "Instagram", "Discord"]),
    partnerCount: 6,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Greylock Partners",
    type: "vc",
    website: "https://greylock.com",
    description: "Leading venture capital firm focused on early-stage consumer and enterprise investments. Known for deep technical expertise.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["enterprise", "consumer", "ai", "infrastructure", "security"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 1000000,
    chequeMax: 50000000,
    thesis: "Investing in the leading consumer and enterprise software companies since 1965.",
    notableDeals: JSON.stringify(["LinkedIn", "Facebook", "Airbnb", "Discord", "Figma", "Roblox"]),
    aum: "$5B+",
    partnerCount: 10,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Index Ventures",
    type: "vc",
    website: "https://www.indexventures.com",
    description: "International VC with offices in San Francisco, London, and Geneva. Strong European roots with global reach.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["fintech", "saas", "marketplace", "gaming", "consumer", "security"]),
    geographies: JSON.stringify(["US", "Europe", "Global"]),
    chequeMin: 500000,
    chequeMax: 100000000,
    thesis: "We partner with founders who are transforming industries and building defining companies.",
    notableDeals: JSON.stringify(["Revolut", "Figma", "Notion", "Plaid", "Deliveroo", "Roblox"]),
    aum: "$11B+",
    partnerCount: 15,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Founders Fund",
    type: "vc",
    website: "https://foundersfund.com",
    description: "VC firm co-founded by Peter Thiel. Invests in revolutionary companies across stages. Known for contrarian thesis.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["ai", "aerospace", "biotech", "enterprise", "crypto", "defense"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 500000,
    chequeMax: 100000000,
    thesis: "We want to live in the future, so we fund the companies building it.",
    notableDeals: JSON.stringify(["SpaceX", "Palantir", "Stripe", "Airbnb", "Spotify", "Anduril"]),
    aum: "$12B+",
    partnerCount: 8,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Bessemer Venture Partners",
    type: "vc",
    website: "https://www.bvp.com",
    description: "One of the oldest VC firms in the US, with deep expertise in cloud computing and SaaS. Known for the Cloud 100 list.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["saas", "cloud", "security", "healthtech", "consumer", "fintech"]),
    geographies: JSON.stringify(["US", "Europe", "Israel", "India"]),
    chequeMin: 500000,
    chequeMax: 75000000,
    thesis: "Partnering with founders to build category-defining businesses since 1911.",
    notableDeals: JSON.stringify(["Shopify", "Twilio", "LinkedIn", "Pinterest", "Canva", "Wix"]),
    aum: "$20B+",
    partnerCount: 15,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Khosla Ventures",
    type: "vc",
    website: "https://www.khoslaventures.com",
    description: "VC firm founded by Vinod Khosla (Sun Microsystems). Strong focus on deep tech, climate, and AI-driven transformation.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["ai", "climate", "healthtech", "enterprise", "robotics", "food-tech"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 250000,
    chequeMax: 50000000,
    thesis: "Funding transformative ideas that have the power to change the world.",
    notableDeals: JSON.stringify(["OpenAI", "DoorDash", "Impossible Foods", "Instacart", "Square"]),
    aum: "$15B+",
    partnerCount: 10,
    source: "seed",
    verified: true,
    enabled: true,
  },

  // ─── GROWTH / CROSSOVER ────────────────────────────────────────────────
  {
    name: "Tiger Global Management",
    type: "vc",
    website: "https://www.tigerglobal.com",
    description: "Crossover investor deploying capital at scale across growth-stage technology companies worldwide.",
    stages: JSON.stringify(["series-b", "growth"]),
    sectors: JSON.stringify(["saas", "fintech", "consumer", "enterprise", "edtech", "marketplace"]),
    geographies: JSON.stringify(["US", "India", "Global"]),
    chequeMin: 10000000,
    chequeMax: 500000000,
    thesis: "Backing ambitious entrepreneurs building transformative technology companies globally.",
    notableDeals: JSON.stringify(["Stripe", "Databricks", "Figma", "Flipkart", "Toast", "Brex"]),
    aum: "$80B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Coatue Management",
    type: "vc",
    website: "https://www.coatue.com",
    description: "Technology-focused crossover fund combining public and private market expertise for deep sector insight.",
    stages: JSON.stringify(["series-b", "growth"]),
    sectors: JSON.stringify(["ai", "enterprise", "fintech", "consumer", "logistics"]),
    geographies: JSON.stringify(["US", "Global"]),
    chequeMin: 10000000,
    chequeMax: 200000000,
    thesis: "Using data-driven insights to identify the best technology companies at every stage.",
    notableDeals: JSON.stringify(["Snap", "DoorDash", "Airtable", "Chime", "Instacart"]),
    aum: "$48B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Insight Partners",
    type: "vc",
    website: "https://www.insightpartners.com",
    description: "Global VC and PE firm focused on scaling high-growth technology companies. Provides ScaleUp services.",
    stages: JSON.stringify(["series-b", "growth"]),
    sectors: JSON.stringify(["saas", "enterprise", "fintech", "security", "data-infrastructure"]),
    geographies: JSON.stringify(["US", "Europe", "Global"]),
    chequeMin: 10000000,
    chequeMax: 200000000,
    thesis: "Scaling ScaleUps — providing capital and operational expertise to accelerate growth.",
    notableDeals: JSON.stringify(["Twitter", "Shopify", "Monday.com", "Wiz", "SentinelOne", "Veeam"]),
    aum: "$80B+",
    partnerCount: 30,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "General Atlantic",
    type: "vc",
    website: "https://www.generalatlantic.com",
    description: "Global growth equity firm providing capital and strategic support to growth companies across sectors.",
    stages: JSON.stringify(["growth"]),
    sectors: JSON.stringify(["fintech", "enterprise", "healthtech", "consumer", "climate"]),
    geographies: JSON.stringify(["US", "Europe", "Asia", "Latin America", "Global"]),
    chequeMin: 50000000,
    chequeMax: 500000000,
    thesis: "Growth equity investing with a long-term, partnership-driven approach.",
    notableDeals: JSON.stringify(["Airbnb", "Alibaba", "Uber", "Slack", "Adyen", "Wise"]),
    aum: "$84B+",
    source: "seed",
    verified: true,
    enabled: true,
  },

  // ─── SEED-FOCUSED ──────────────────────────────────────────────────────
  {
    name: "Y Combinator",
    type: "accelerator",
    website: "https://www.ycombinator.com",
    description: "The world's most famous startup accelerator. Invests $500K in each batch company for 7% equity. Two batches per year.",
    stages: JSON.stringify(["pre-seed"]),
    sectors: JSON.stringify(["saas", "ai", "fintech", "healthtech", "enterprise", "consumer", "marketplace", "biotech", "hardware"]),
    geographies: JSON.stringify(["Global"]),
    chequeMin: 500000,
    chequeMax: 500000,
    thesis: "Make something people want. Apply to build your startup with the best community in tech.",
    notableDeals: JSON.stringify(["Airbnb", "Stripe", "Dropbox", "Coinbase", "DoorDash", "Reddit", "Twitch"]),
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Techstars",
    type: "accelerator",
    website: "https://www.techstars.com",
    description: "Global accelerator network running 40+ programs worldwide. Provides $120K investment, mentorship, and community.",
    stages: JSON.stringify(["pre-seed"]),
    sectors: JSON.stringify(["saas", "fintech", "healthtech", "enterprise", "consumer", "climate", "space"]),
    geographies: JSON.stringify(["US", "Europe", "Global"]),
    chequeMin: 120000,
    chequeMax: 120000,
    thesis: "Helping entrepreneurs succeed everywhere through mentorship, capital, and community.",
    notableDeals: JSON.stringify(["Sendgrid", "Sphero", "DigitalOcean", "Zipline", "ClassPass"]),
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "First Round Capital",
    type: "vc",
    website: "https://firstround.com",
    description: "Seed-stage VC known for building the strongest founder community. Offers platform services and knowledge resources.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["saas", "enterprise", "marketplace", "consumer", "fintech"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 500000,
    chequeMax: 5000000,
    thesis: "We are the partner seed-stage founders deserve. We invest first and support longest.",
    notableDeals: JSON.stringify(["Uber", "Square", "Notion", "Roblox", "Warby Parker", "Flatiron Health"]),
    aum: "$3B+",
    partnerCount: 10,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Precursor Ventures",
    type: "vc",
    website: "https://precursorvc.com",
    description: "Pre-seed and seed focused VC led by Charles Hudson. Known for backing diverse founders and underserved markets.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["saas", "fintech", "marketplace", "consumer", "proptech"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 100000,
    chequeMax: 1000000,
    thesis: "Investing at the earliest stages in founders building products people need.",
    notableDeals: JSON.stringify(["Haus", "Nuro", "Traba"]),
    aum: "$175M",
    partnerCount: 3,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Hustle Fund",
    type: "vc",
    website: "https://www.hustlefund.vc",
    description: "Pre-seed VC backing scrappy founders globally. Known for fast decisions, small checks, and high volume.",
    stages: JSON.stringify(["pre-seed"]),
    sectors: JSON.stringify(["saas", "marketplace", "consumer", "fintech", "edtech"]),
    geographies: JSON.stringify(["US", "Global"]),
    chequeMin: 25000,
    chequeMax: 500000,
    thesis: "Speed and hustle matter more than pedigree. We back founders who move fast.",
    notableDeals: JSON.stringify(["Snackpass", "Fathom", "Paperspace"]),
    aum: "$130M",
    partnerCount: 4,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Floodgate",
    type: "vc",
    website: "https://floodgate.com",
    description: "Seed-stage VC focused on backing visionary founders with breakthrough ideas. Known for the 'thunder lizard' thesis.",
    stages: JSON.stringify(["seed"]),
    sectors: JSON.stringify(["consumer", "enterprise", "fintech", "ai", "marketplace"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 500000,
    chequeMax: 5000000,
    thesis: "We back 'thunder lizards' — startups that can grow massive and reshape markets.",
    notableDeals: JSON.stringify(["Lyft", "Twitch", "Twitter", "Okta", "Demandbase"]),
    aum: "$1B+",
    partnerCount: 4,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "SV Angel",
    type: "vc",
    website: "https://svangel.com",
    description: "Seed-stage fund with deep Silicon Valley roots. Provides introductions and strategic advice beyond capital.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["saas", "consumer", "enterprise", "fintech", "marketplace"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 100000,
    chequeMax: 1000000,
    thesis: "Investing in the best entrepreneurs at the earliest stages.",
    notableDeals: JSON.stringify(["Airbnb", "Pinterest", "Stripe", "Twitter", "Slack"]),
    source: "seed",
    verified: true,
    enabled: true,
  },

  // ─── NOTABLE ANGELS ────────────────────────────────────────────────────
  {
    name: "Naval Ravikant",
    type: "angel",
    description: "Co-founder of AngelList. One of Silicon Valley's most prolific angel investors with 200+ investments.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["saas", "fintech", "crypto", "consumer", "ai", "marketplace"]),
    geographies: JSON.stringify(["US", "Global"]),
    chequeMin: 25000,
    chequeMax: 500000,
    thesis: "Invest in founders with specific knowledge and leverage. Seek asymmetric upside.",
    notableDeals: JSON.stringify(["Twitter", "Uber", "Yammer", "Wish", "Postmates", "AngelList"]),
    twitter: "https://twitter.com/naval",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Elad Gil",
    type: "angel",
    website: "https://eladgil.com",
    description: "Prolific angel investor, author of 'High Growth Handbook'. Former VP at Twitter and co-founder at Color Genomics.",
    stages: JSON.stringify(["seed", "series-a"]),
    sectors: JSON.stringify(["ai", "enterprise", "saas", "healthtech", "crypto", "biotech"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 100000,
    chequeMax: 5000000,
    thesis: "Back exceptional founders building transformative technology companies.",
    notableDeals: JSON.stringify(["Airbnb", "Coinbase", "Stripe", "Square", "Figma", "Airtable", "Notion"]),
    twitter: "https://twitter.com/eloelo",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Jason Calacanis",
    type: "angel",
    website: "https://calacanis.com",
    description: "Angel investor, podcaster (This Week in Startups), and founder of LAUNCH. Known for early Uber investment.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["saas", "consumer", "marketplace", "ai", "fintech"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 25000,
    chequeMax: 250000,
    thesis: "Invest in founders who are relentless, ethical, and building real businesses.",
    notableDeals: JSON.stringify(["Uber", "Robinhood", "Calm", "Thumbtack", "Desktop Metal"]),
    twitter: "https://twitter.com/Jason",
    source: "seed",
    verified: true,
    enabled: true,
  },

  // ─── SECTOR-SPECIFIC ──────────────────────────────────────────────────
  {
    name: "Ribbit Capital",
    type: "vc",
    website: "https://ribbitcap.com",
    description: "VC exclusively focused on fintech. Deep expertise in financial services disruption and regulatory landscapes.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["fintech"]),
    geographies: JSON.stringify(["US", "Latin America", "Global"]),
    chequeMin: 1000000,
    chequeMax: 50000000,
    thesis: "Backing the next generation of financial services companies. Fintech is everything.",
    notableDeals: JSON.stringify(["Robinhood", "Coinbase", "Nubank", "Credit Karma", "Revolut", "Brex"]),
    aum: "$4B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Lux Capital",
    type: "vc",
    website: "https://luxcapital.com",
    description: "VC firm specializing in deep tech — science and engineering breakthroughs. Known for contrarian, long-horizon bets.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["ai", "robotics", "aerospace", "biotech", "climate", "defense"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 1000000,
    chequeMax: 50000000,
    thesis: "Investing at the frontier of science and technology to back unconventional thinkers.",
    notableDeals: JSON.stringify(["Anduril", "Saildrone", "Eikon Therapeutics", "Miso Robotics"]),
    aum: "$5B+",
    partnerCount: 8,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "a16z crypto",
    type: "vc",
    website: "https://a16zcrypto.com",
    description: "Dedicated crypto/web3 fund from Andreessen Horowitz. Invests in infrastructure, DeFi, NFTs, and DAOs.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["crypto", "defi", "web3", "infrastructure"]),
    geographies: JSON.stringify(["US", "Global"]),
    chequeMin: 1000000,
    chequeMax: 100000000,
    thesis: "Crypto and web3 will transform finance, gaming, social, and the internet itself.",
    notableDeals: JSON.stringify(["Coinbase", "Uniswap", "Solana", "Yuga Labs", "dYdX", "Phantom"]),
    aum: "$7.6B",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "General Catalyst",
    type: "vc",
    website: "https://www.generalcatalyst.com",
    description: "Multi-stage VC known for building enduring companies with a focus on 'responsible innovation.'",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["enterprise", "healthtech", "fintech", "consumer", "climate", "ai"]),
    geographies: JSON.stringify(["US", "Europe", "Global"]),
    chequeMin: 500000,
    chequeMax: 100000000,
    thesis: "Building enduring companies through responsible innovation.",
    notableDeals: JSON.stringify(["Stripe", "Airbnb", "Snap", "HubSpot", "Lemonade", "Livongo"]),
    aum: "$25B+",
    partnerCount: 20,
    source: "seed",
    verified: true,
    enabled: true,
  },

  // ─── GEO-DIVERSE ──────────────────────────────────────────────────────
  {
    name: "Balderton Capital",
    type: "vc",
    website: "https://www.balderton.com",
    description: "Europe's leading early-stage VC. Exclusively backs European-born tech companies.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["saas", "fintech", "healthtech", "marketplace", "ai", "consumer"]),
    geographies: JSON.stringify(["Europe"]),
    chequeMin: 500000,
    chequeMax: 30000000,
    thesis: "The next generation of technology leaders will come from Europe.",
    notableDeals: JSON.stringify(["Revolut", "GoCardless", "Citymapper", "Nutmeg", "Prodigy Finance"]),
    aum: "$5B+",
    partnerCount: 8,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Peak XV Partners (Sequoia India/SEA)",
    type: "vc",
    website: "https://peakxv.com",
    description: "Formerly Sequoia India & Southeast Asia. Largest VC in the region backing founders from seed to IPO.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["fintech", "saas", "consumer", "edtech", "healthtech", "logistics"]),
    geographies: JSON.stringify(["India", "Southeast Asia"]),
    chequeMin: 100000,
    chequeMax: 100000000,
    thesis: "Partnering with exceptional founders in India and Southeast Asia.",
    notableDeals: JSON.stringify(["Zomato", "Byjus", "Razorpay", "Gojek", "Pine Labs", "Cred"]),
    aum: "$9B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "SoftBank Vision Fund",
    type: "vc",
    website: "https://visionfund.com",
    description: "The world's largest technology-focused investment fund. Known for massive growth and late-stage bets.",
    stages: JSON.stringify(["growth"]),
    sectors: JSON.stringify(["ai", "fintech", "logistics", "consumer", "enterprise", "mobility"]),
    geographies: JSON.stringify(["US", "Asia", "Europe", "Latin America", "Global"]),
    chequeMin: 100000000,
    chequeMax: 1000000000,
    thesis: "Investing in transformative technology at scale to accelerate the AI revolution.",
    notableDeals: JSON.stringify(["Uber", "WeWork", "DoorDash", "Coupang", "ByteDance", "Arm"]),
    aum: "$100B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Naspers / Prosus",
    type: "corporate",
    website: "https://www.prosus.com",
    description: "Global consumer internet investment group, spun out of South African media company Naspers. Focuses on emerging markets.",
    stages: JSON.stringify(["series-b", "growth"]),
    sectors: JSON.stringify(["fintech", "edtech", "food-delivery", "classifieds", "consumer"]),
    geographies: JSON.stringify(["Global", "Africa", "India", "Southeast Asia", "Europe"]),
    chequeMin: 10000000,
    chequeMax: 500000000,
    thesis: "Investing in high-growth consumer internet companies in emerging and developed markets.",
    notableDeals: JSON.stringify(["Tencent", "Swiggy", "PayU", "OLX", "Byju's"]),
    aum: "$100B+",
    source: "seed",
    verified: true,
    enabled: true,
  },

  // ─── ADDITIONAL SEED / EARLY ───────────────────────────────────────────
  {
    name: "500 Global",
    type: "vc",
    website: "https://500.co",
    description: "Global multi-stage VC with one of the most active seed portfolios in the world. 2,700+ portfolio companies.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["saas", "fintech", "consumer", "marketplace", "edtech", "healthtech"]),
    geographies: JSON.stringify(["US", "Global", "Latin America", "MENA", "Southeast Asia"]),
    chequeMin: 50000,
    chequeMax: 2000000,
    thesis: "Backing founders who represent the diversity and potential of the global economy.",
    notableDeals: JSON.stringify(["Canva", "Grab", "Talkdesk", "Credit Karma", "Udemy"]),
    aum: "$2.8B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "True Ventures",
    type: "vc",
    website: "https://trueventures.com",
    description: "Seed and early-stage VC with a founder-first philosophy. Known for deep engagement and True University community.",
    stages: JSON.stringify(["seed", "series-a"]),
    sectors: JSON.stringify(["saas", "consumer", "hardware", "ai", "sustainability"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 500000,
    chequeMax: 10000000,
    thesis: "Founders first. We invest in people, then ideas, then markets.",
    notableDeals: JSON.stringify(["Peloton", "Ring", "Fitbit", "Blue Bottle Coffee", "Hashicorp"]),
    aum: "$3B+",
    partnerCount: 8,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Union Square Ventures",
    type: "vc",
    website: "https://www.usv.com",
    description: "Thesis-driven VC focused on networks, platforms, and protocols. Known for early internet and crypto investments.",
    stages: JSON.stringify(["seed", "series-a"]),
    sectors: JSON.stringify(["marketplace", "crypto", "fintech", "climate", "healthtech"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 1000000,
    chequeMax: 25000000,
    thesis: "Invest in large networks of engaged users, differentiated through user experience.",
    notableDeals: JSON.stringify(["Twitter", "Tumblr", "Etsy", "Kickstarter", "Coinbase", "Cloudflare"]),
    aum: "$2B+",
    partnerCount: 5,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "NEA (New Enterprise Associates)",
    type: "vc",
    website: "https://www.nea.com",
    description: "One of the world's largest and most active VCs with 40+ years of investing across stages and sectors.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["enterprise", "healthtech", "fintech", "consumer", "ai", "biotech"]),
    geographies: JSON.stringify(["US", "Europe", "China", "India"]),
    chequeMin: 500000,
    chequeMax: 100000000,
    thesis: "Partnering with visionary founders building world-changing companies across sectors.",
    notableDeals: JSON.stringify(["Salesforce", "Uber", "Cloudflare", "Databricks", "Robinhood", "Plaid"]),
    aum: "$25B+",
    partnerCount: 25,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Initialized Capital",
    type: "vc",
    website: "https://initialized.com",
    description: "Seed-stage VC co-founded by Alexis Ohanian (Reddit) and Garry Tan (now YC President). Community-driven approach.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["saas", "consumer", "fintech", "ai", "marketplace", "climate"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 250000,
    chequeMax: 3000000,
    thesis: "We bet on people over plans. Seed-stage capital with founder-first values.",
    notableDeals: JSON.stringify(["Coinbase", "Flexport", "Instacart", "Cruise", "Ro"]),
    aum: "$1B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Plug and Play",
    type: "accelerator",
    website: "https://www.plugandplaytechcenter.com",
    description: "Global innovation platform connecting startups with corporations. Runs 50+ accelerator programs annually.",
    stages: JSON.stringify(["pre-seed", "seed"]),
    sectors: JSON.stringify(["fintech", "healthtech", "supply-chain", "mobility", "enterprise", "insurtech"]),
    geographies: JSON.stringify(["US", "Europe", "Asia", "MENA", "Global"]),
    chequeMin: 25000,
    chequeMax: 500000,
    thesis: "Connecting the best startups with the world's largest corporations for mutual growth.",
    notableDeals: JSON.stringify(["PayPal", "Dropbox", "LendingClub", "N26"]),
    source: "seed",
    verified: true,
    enabled: true,
  },

  // ─── ADDITIONAL NOTABLE FIRMS ──────────────────────────────────────────
  {
    name: "Kleiner Perkins",
    type: "vc",
    website: "https://www.kleinerperkins.com",
    description: "Legendary Silicon Valley VC with 50+ years of history. Early backers of Amazon, Google, and Genentech.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["enterprise", "consumer", "fintech", "healthtech", "climate", "ai"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 1000000,
    chequeMax: 50000000,
    thesis: "Backing founders who see possibilities before they become obvious.",
    notableDeals: JSON.stringify(["Amazon", "Google", "Slack", "DoorDash", "Figma", "Nuro"]),
    aum: "$9B+",
    partnerCount: 10,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "GV (Google Ventures)",
    type: "corporate",
    website: "https://www.gv.com",
    description: "Alphabet's independent VC arm. Offers unique access to Google resources, expertise, and talent network.",
    stages: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["ai", "enterprise", "healthtech", "consumer", "robotics", "security"]),
    geographies: JSON.stringify(["US", "Europe"]),
    chequeMin: 500000,
    chequeMax: 50000000,
    thesis: "Investing across all stages with the resources and network of Alphabet behind us.",
    notableDeals: JSON.stringify(["Uber", "Slack", "Stripe", "Nest", "Gitlab", "Duolingo"]),
    aum: "$8B+",
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Craft Ventures",
    type: "vc",
    website: "https://www.craftventures.com",
    description: "VC firm led by David Sacks (PayPal, Yammer). Focuses on enterprise SaaS and marketplace companies.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["saas", "enterprise", "marketplace", "fintech", "ai"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 1000000,
    chequeMax: 25000000,
    thesis: "We invest in founders who understand how to build products people love and businesses that scale.",
    notableDeals: JSON.stringify(["SpaceX", "Palantir", "Bird", "ClickUp", "Sourcegraph"]),
    aum: "$3B+",
    partnerCount: 5,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "Atomico",
    type: "vc",
    website: "https://www.atomico.com",
    description: "European VC founded by Niklas Zennstrom (Skype co-founder). Publishes the annual State of European Tech report.",
    stages: JSON.stringify(["series-a", "series-b", "growth"]),
    sectors: JSON.stringify(["saas", "fintech", "healthtech", "climate", "marketplace", "ai"]),
    geographies: JSON.stringify(["Europe"]),
    chequeMin: 5000000,
    chequeMax: 75000000,
    thesis: "Europe is building world-class technology companies. We are here to support them.",
    notableDeals: JSON.stringify(["Klarna", "Supercell", "Graphcore", "Compass", "MessageBird"]),
    aum: "$5B+",
    partnerCount: 8,
    source: "seed",
    verified: true,
    enabled: true,
  },
  {
    name: "8VC",
    type: "vc",
    website: "https://8vc.com",
    description: "VC firm led by Joe Lonsdale (Palantir co-founder). Focuses on transforming legacy industries with technology.",
    stages: JSON.stringify(["seed", "series-a", "series-b"]),
    sectors: JSON.stringify(["enterprise", "fintech", "healthtech", "logistics", "defense", "proptech"]),
    geographies: JSON.stringify(["US"]),
    chequeMin: 500000,
    chequeMax: 50000000,
    thesis: "Transforming industries through technology — targeting sectors ripe for disruption.",
    notableDeals: JSON.stringify(["Palantir", "Oculus", "Oscar Health", "Joby Aviation", "Wish"]),
    aum: "$6B+",
    partnerCount: 6,
    source: "seed",
    verified: true,
    enabled: true,
  },
];
